// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNLH6SK95J1n4gtJ6oSnVF17iYIenrm4',
    appId: '1:729394554037:web:55e29a8c327d997651cafc',
    messagingSenderId: '729394554037',
    projectId: 'playstore-1dc84',
    authDomain: 'playstore-1dc84.firebaseapp.com',
    storageBucket: 'playstore-1dc84.firebasestorage.app',
    measurementId: 'G-W0Q4HJT28K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9Cktlp54AzK1JO9sLe69xBfeYA8b-QA',
    appId: '1:729394554037:android:29f0a71e7aa0e6a151cafc',
    messagingSenderId: '729394554037',
    projectId: 'playstore-1dc84',
    storageBucket: 'playstore-1dc84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePvl1ts-oEqpoib0S9IHRVYObn5NzlF8',
    appId: '1:729394554037:ios:8f9f1a4c6ae2f11851cafc',
    messagingSenderId: '729394554037',
    projectId: 'playstore-1dc84',
    storageBucket: 'playstore-1dc84.firebasestorage.app',
    iosClientId: '729394554037-2579vchdnd9tb2um7j9i2ap8qmsbtqdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.zorrowCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDePvl1ts-oEqpoib0S9IHRVYObn5NzlF8',
    appId: '1:729394554037:ios:8f9f1a4c6ae2f11851cafc',
    messagingSenderId: '729394554037',
    projectId: 'playstore-1dc84',
    storageBucket: 'playstore-1dc84.firebasestorage.app',
    iosClientId: '729394554037-2579vchdnd9tb2um7j9i2ap8qmsbtqdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.zorrowCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNLH6SK95J1n4gtJ6oSnVF17iYIenrm4',
    appId: '1:729394554037:web:20c0bb350c394ab251cafc',
    messagingSenderId: '729394554037',
    projectId: 'playstore-1dc84',
    authDomain: 'playstore-1dc84.firebaseapp.com',
    storageBucket: 'playstore-1dc84.firebasestorage.app',
    measurementId: 'G-DTB8ZC30J6',
  );
}
